### ISSUE TITLE
[BUG] 错误的名单列表

### ISSUE THREAD

**Issue by Himself65** [avoid-huawei-navy/avoid-huawei-navy#3]
http://www.zhihu.com/pin/1151485297018654720

评论区说名单中有反串黑人员

**Comment by moranzcw** [comment]
已经修了

**Comment by Himself65** [comment]
Fixed on https://github.com/avoid-huawei-navy/avoid-huawei-navy/commit/5ba4ddc3781717069df821ad46a501ebe12b06a2
